/* 卡面文字摘自玩法书_V1.2.md；数值修改须同步规则书。 */
export const GODS = [
  {
    id: 0,
    name: '毛伊',
    original: 'Māui',
    culture: '毛利',
    elements: ['骨', '潮', '风'],
    effect: '将自己的一张供奉及印记移到另一神的匹配空槽；补满时视你为收尾者。',
    story: '海仍在潮起潮落，人们却忘了岛屿曾从哪里升起。',
    image: '/art/god01.webp',
  },
  {
    id: 1,
    name: '希内努伊特波',
    original: 'Hine-nui-te-pō',
    culture: '毛利',
    elements: ['骨', '潮', '星'],
    effect: '本回合安魂也可选择只有一点风化的神，其余代价正常。',
    story: '亡者仍踏入长夜，活人却忘了怎样好好告别。',
    image: '/art/god02.webp',
  },
  {
    id: 2,
    name: '贝雅薇',
    original: 'Beaivi',
    culture: '萨米',
    elements: ['炎', '星', '风'],
    effect: '为至多两尊不同的在场神各移除一点风化。',
    story: '太阳仍照在雪地上，人们却忘了为归人辨认方向。',
    image: '/art/god03.webp',
  },
  {
    id: 3,
    name: '霍拉加勒斯',
    original: 'Horagalles',
    culture: '萨米',
    elements: ['潮', '风', '星'],
    effect: '交换两尊在场神的风化数量，重新调整横竖状态。',
    story: '雷声仍越过山脊，人们却忘了风雨何时将至。',
    image: '/art/god04.webp',
  },
  {
    id: 4,
    name: '火姥神',
    original: 'Ape-huci-kamuy',
    culture: '阿伊努',
    elements: ['骨', '炎', '星'],
    effect: '自己的心智上限恢复一点，并摸一张牌。',
    story: '炉火仍然燃烧，人们却忘了为归来者留一个位置。',
    image: '/art/god05.webp',
  },
  {
    id: 5,
    name: '村落守护神',
    original: 'Kotan-kor-kamuy',
    culture: '阿伊努',
    elements: ['骨', '风', '潮'],
    effect: '可以移除一尊在场神的禁忌。然后摸一张牌。',
    story: '枭仍守望村落，人们却再也听不懂它的警告。',
    image: '/art/god06.webp',
  },
  {
    id: 6,
    name: '埃舒',
    original: 'Èṣù',
    culture: '约鲁巴',
    elements: ['风', '炎', '星'],
    effect: '选择一尊在场神：没有禁忌则放置一枚，已有则移除。',
    story: '路口依旧通向四方，人们却忘了该先向谁问路。',
    image: '/art/god07.webp',
  },
  {
    id: 7,
    name: '奥贡',
    original: 'Ògún',
    culture: '约鲁巴',
    elements: ['骨', '炎', '风'],
    effect:
      '本回合下一次从手牌放置的供奉可将任意牌当骨或炎，并免除、移除目标神的禁忌。该牌在槽中视为所选语素，离开槽后恢复印刷语素。',
    story: '铁器仍然锋利，人们却忘了如何为彼此开路。',
    image: '/art/god08.webp',
  },
  {
    id: 8,
    name: '玉米神',
    original: 'Maya Maize God',
    culture: '玛雅',
    elements: ['骨', '潮', '炎'],
    effect: '从弃牌堆取回至多两张不同语素的牌，不能取本次祈神支付的牌。',
    story: '玉米依旧发芽，人们却忘了收获之后还要留种。',
    image: '/art/god09.webp',
  },
  {
    id: 9,
    name: '雨神',
    original: 'Chahk',
    culture: '玛雅',
    elements: ['潮', '风', '星'],
    effect: '为一尊零或一点风化的在场神增加一点风化，然后摸一张牌。',
    story: '雨仍从天而降，人们却忘了何时播种、何时避洪。',
    image: '/art/god10.webp',
  },
  {
    id: 10,
    name: '乌伦·阿尔·托伊恩',
    original: 'Ürüng Aar Toyon',
    culture: '萨哈',
    elements: ['骨', '炎', '星'],
    effect:
      '本回合下一次从手牌放置的供奉可将任意牌当星；该牌在槽中视为星，离开槽后恢复印刷语素。完成该次供奉后，自己心智恢复一点。',
    story: '天空依旧高远，人们抬头时却只看见一片空白。',
    image: '/art/god11.webp',
  },
  {
    id: 11,
    name: '巴亚奈',
    original: 'Bayanay',
    culture: '萨哈',
    elements: ['炎', '潮', '风'],
    effect: '查看记忆堆顶至多三张，取一张入手，其余弃置。',
    story: '雪地仍有兽迹，人们却忘了取用之前也要先请求。',
    image: '/art/god12.webp',
  },
] as const;
export const SHAMANS = [
  {
    id: 0,
    name: '渡魂人',
    timing: '主动，占辅助',
    effect:
      '将自己一张供奉及印记移到另一神的匹配空槽；补满时视你为收尾者，立即觉醒。',
  },
  {
    id: 1,
    name: '听冬者',
    timing: '主动，占辅助',
    effect: '查看风暴顶至多两张，可交换顺序。',
  },
  {
    id: 2,
    name: '刻骨者',
    timing: '被动',
    effect:
      '供奉时可将任意牌当骨；该牌在槽中视为骨，离开槽后恢复印刷语素。安魂祭品仍须使用印有骨的牌。',
  },
  {
    id: 3,
    name: '守火人',
    timing: '主动，占辅助',
    effect:
      '燃烧一张手牌，为一尊两点风化的神移除一点风化，再结算烧牌巫术；不额外摸牌。',
  },
  {
    id: 4,
    name: '织名者',
    timing: '被动',
    effect:
      '每当一尊有你供奉的神被其他萨满唤醒或众声觉醒时，你额外获得一点余音。',
  },
  {
    id: 5,
    name: '问途者',
    timing: '主动，占辅助，每局一次',
    effect:
      '本回合从手牌放置供奉时，可将任意一张手牌当任意语素；该牌在槽中视为所选语素，离开槽后恢复印刷语素。发动时勾选已用。',
  },
] as const;
export const STORMS = [
  {
    id: 0,
    name: '初冬 · 白霜',
    targets: [0],
    season: 0,
    image: '/art/storm01.webp',
  },
  {
    id: 1,
    name: '初冬 · 薄冰',
    targets: [1],
    season: 0,
    image: '/art/storm02.webp',
  },
  {
    id: 2,
    name: '初冬 · 远风',
    targets: [2],
    season: 0,
    image: '/art/storm03.webp',
  },
  {
    id: 3,
    name: '初冬 · 雪痕',
    targets: [3],
    season: 0,
    image: '/art/storm04.webp',
  },
  {
    id: 4,
    name: '深冬 · 凛夜',
    targets: [0],
    season: 1,
    image: '/art/storm05.webp',
  },
  {
    id: 5,
    name: '深冬 · 冻河',
    targets: [1],
    season: 1,
    image: '/art/storm06.webp',
  },
  {
    id: 6,
    name: '深冬 · 寒林',
    targets: [2],
    season: 1,
    image: '/art/storm07.webp',
  },
  {
    id: 7,
    name: '深冬 · 无月',
    targets: [3],
    season: 1,
    image: '/art/storm08.webp',
  },
  {
    id: 8,
    name: '极夜 · 横雪',
    targets: [0, 2],
    season: 2,
    image: '/art/storm09.webp',
  },
  {
    id: 9,
    name: '极夜 · 断灯',
    targets: [1, 3],
    season: 2,
    image: '/art/storm10.webp',
  },
  {
    id: 10,
    name: '极夜 · 黑潮',
    targets: [0, 1],
    season: 2,
    image: '/art/storm11.webp',
  },
  {
    id: 11,
    name: '极夜 · 长眠',
    targets: [2, 3],
    season: 2,
    image: '/art/storm12.webp',
  },
] as const;
